WITH AvgPrices AS (
    SELECT I_CATEGORY, AVG(I_CURRENT_PRICE) AS AvgCurrentPrice
    FROM ITEM
    GROUP BY I_CATEGORY
)

SELECT A.CA_STATE STATE, COUNT(*) CNT 
FROM 
    STORE_SALES S 
    JOIN DATE_DIM D ON S.SS_SOLD_DATE_SK = D.D_DATE_SK AND D.D_YEAR = 2002 AND D.D_MOY = 3
    JOIN CUSTOMER C ON C.C_CUSTOMER_SK = S.SS_CUSTOMER_SK
    JOIN CUSTOMER_ADDRESS A ON A.CA_ADDRESS_SK = C.C_CURRENT_ADDR_SK
    JOIN ITEM I ON I.I_ITEM_SK = S.SS_ITEM_SK
    JOIN AvgPrices AP ON I.I_CATEGORY = AP.I_CATEGORY
WHERE I.I_CURRENT_PRICE > 1.2 * AP.AvgCurrentPrice
GROUP BY A.CA_STATE 
HAVING COUNT(*) >= 10 
ORDER BY CNT, A.CA_STATE 
LIMIT 100;
