CREATE VIEW MV_INV AS
    SELECT
        W_WAREHOUSE_NAME,
        W_WAREHOUSE_SK,
        I_ITEM_SK,
        D_MOY,
        D_YEAR,
        STDDEV_SAMP(INV_QUANTITY_ON_HAND) AS STDEV,
        AVG(INV_QUANTITY_ON_HAND) AS MEAN
    FROM DATE_DIM
        JOIN INVENTORY ON INV_DATE_SK = D_DATE_SK
        JOIN ITEM ON INV_ITEM_SK = I_ITEM_SK
        JOIN WAREHOUSE ON INV_WAREHOUSE_SK = W_WAREHOUSE_SK
    WHERE (D_YEAR = 2000 OR D_YEAR = 2001)
    GROUP BY W_WAREHOUSE_NAME, W_WAREHOUSE_SK, I_ITEM_SK, D_MOY, D_YEAR;

WITH INV AS (
    SELECT 
        W_WAREHOUSE_NAME,
        W_WAREHOUSE_SK,
        I_ITEM_SK,
        D_MOY,
        STDEV,
        MEAN,
        CASE WHEN MEAN = 0 THEN NULL ELSE STDEV / MEAN END AS COV
    FROM MV_INV
    WHERE D_YEAR = 2000 AND (MEAN = 0 OR STDEV / MEAN > 1)
)
SELECT
    INV1.W_WAREHOUSE_SK,
    INV1.I_ITEM_SK,
    INV1.D_MOY,
    INV1.MEAN,
    INV1.COV,
    INV2.W_WAREHOUSE_SK,
    INV2.I_ITEM_SK,
    INV2.D_MOY,
    INV2.MEAN,
    INV2.COV
FROM INV INV1, INV INV2
WHERE
    INV1.I_ITEM_SK = INV2.I_ITEM_SK
    AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
    AND INV1.D_MOY = 2
    AND INV2.D_MOY = 2 + 1
ORDER BY
    INV1.W_WAREHOUSE_SK,
    INV1.I_ITEM_SK,
    INV1.D_MOY,
    INV1.MEAN,
    INV1.COV,
    INV2.D_MOY,
    INV2.MEAN,
    INV2.COV;
    
WITH INV AS (
    SELECT 
        W_WAREHOUSE_NAME,
        W_WAREHOUSE_SK,
        I_ITEM_SK,
        D_MOY,
        STDEV,
        MEAN,
        CASE WHEN MEAN = 0 THEN NULL ELSE STDEV / MEAN END AS COV
    FROM MV_INV
    WHERE D_YEAR = 2001 AND (MEAN = 0 OR STDEV / MEAN > 1)
)
SELECT
    INV1.W_WAREHOUSE_SK,
    INV1.I_ITEM_SK,
    INV1.D_MOY,
    INV1.MEAN,
    INV1.COV,
    INV2.W_WAREHOUSE_SK,
    INV2.I_ITEM_SK,
    INV2.D_MOY,
    INV2.MEAN,
    INV2.COV
FROM INV INV1, INV INV2
WHERE
    INV1.I_ITEM_SK = INV2.I_ITEM_SK
    AND INV1.W_WAREHOUSE_SK = INV2.W_WAREHOUSE_SK
    AND INV1.D_MOY = 2
    AND INV2.D_MOY = 2 + 1
    AND INV1.COV > 1.5
ORDER BY
    INV1.W_WAREHOUSE_SK,
    INV1.I_ITEM_SK,
    INV1.D_MOY,
    INV1.MEAN,
    INV1.COV,
    INV2.D_MOY,
    INV2.MEAN,
    INV2.COV;