WITH STORE_SALES_YEAR_TOTAL AS (
    SELECT
        C_CUSTOMER_ID AS CUSTOMER_ID,
        C_FIRST_NAME AS CUSTOMER_FIRST_NAME,
        C_LAST_NAME AS CUSTOMER_LAST_NAME,
        C_PREFERRED_CUST_FLAG AS CUSTOMER_PREFERRED_CUST_FLAG,
        C_BIRTH_COUNTRY AS CUSTOMER_BIRTH_COUNTRY,
        C_LOGIN AS CUSTOMER_LOGIN,
        C_EMAIL_ADDRESS AS CUSTOMER_EMAIL_ADDRESS,
        D_YEAR AS DYEAR,
        SUM(SS_EXT_LIST_PRICE - SS_EXT_DISCOUNT_AMT) AS YEAR_TOTAL
    FROM
        CUSTOMER,
        STORE_SALES,
        DATE_DIM
    WHERE
        C_CUSTOMER_SK = SS_CUSTOMER_SK
        AND SS_SOLD_DATE_SK = D_DATE_SK
        AND (D_YEAR = 2001 OR D_YEAR = 2002)
    GROUP BY
        C_CUSTOMER_ID,
        C_FIRST_NAME,
        C_LAST_NAME,
        C_PREFERRED_CUST_FLAG,
        C_BIRTH_COUNTRY,
        C_LOGIN,
        C_EMAIL_ADDRESS,
        D_YEAR
),
WEB_SALES_YEAR_TOTAL AS (
    SELECT
        C_CUSTOMER_ID AS CUSTOMER_ID,
        C_FIRST_NAME AS CUSTOMER_FIRST_NAME,
        C_LAST_NAME AS CUSTOMER_LAST_NAME,
        C_PREFERRED_CUST_FLAG AS CUSTOMER_PREFERRED_CUST_FLAG,
        C_BIRTH_COUNTRY AS CUSTOMER_BIRTH_COUNTRY,
        C_LOGIN AS CUSTOMER_LOGIN,
        C_EMAIL_ADDRESS AS CUSTOMER_EMAIL_ADDRESS,
        D_YEAR AS DYEAR,
        SUM(WS_EXT_LIST_PRICE - WS_EXT_DISCOUNT_AMT) AS YEAR_TOTAL
    FROM
        CUSTOMER,
        WEB_SALES,
        DATE_DIM
    WHERE
        C_CUSTOMER_SK = WS_BILL_CUSTOMER_SK
        AND WS_SOLD_DATE_SK = D_DATE_SK
        AND (D_YEAR = 2001 OR D_YEAR = 2002)
    GROUP BY
        C_CUSTOMER_ID,
        C_FIRST_NAME,
        C_LAST_NAME,
        C_PREFERRED_CUST_FLAG,
        C_BIRTH_COUNTRY,
        C_LOGIN,
        C_EMAIL_ADDRESS,
        D_YEAR
)
SELECT
    S2.CUSTOMER_ID,
    S2.CUSTOMER_FIRST_NAME,
    S2.CUSTOMER_LAST_NAME,
    S2.CUSTOMER_BIRTH_COUNTRY
FROM
    STORE_SALES_YEAR_TOTAL S1
JOIN
    STORE_SALES_YEAR_TOTAL S2 ON S1.CUSTOMER_ID = S2.CUSTOMER_ID AND S1.DYEAR = 2001 AND S2.DYEAR = 2002
JOIN
    WEB_SALES_YEAR_TOTAL W1 ON S1.CUSTOMER_ID = W1.CUSTOMER_ID AND W1.DYEAR = 2001
JOIN
    WEB_SALES_YEAR_TOTAL W2 ON S1.CUSTOMER_ID = W2.CUSTOMER_ID AND W2.DYEAR = 2002
WHERE
    S1.YEAR_TOTAL > 0
    AND W1.YEAR_TOTAL > 0
    AND (CASE WHEN W1.YEAR_TOTAL > 0 THEN W2.YEAR_TOTAL / W1.YEAR_TOTAL ELSE 0.0 END) 
        > (CASE WHEN S1.YEAR_TOTAL > 0 THEN S2.YEAR_TOTAL / S1.YEAR_TOTAL ELSE 0.0 END)
ORDER BY
    S2.CUSTOMER_ID,
    S2.CUSTOMER_FIRST_NAME,
    S2.CUSTOMER_LAST_NAME,
    S2.CUSTOMER_BIRTH_COUNTRY
LIMIT 100;
