WITH WS AS ( 
    SELECT WS_ITEM_SK
           , WS_BILL_CUSTOMER_SK WS_CUSTOMER_SK
           , SUM(WS_QUANTITY) WS_QTY
           , SUM(WS_WHOLESALE_COST) WS_WC
           , SUM(WS_SALES_PRICE) WS_SP 
    FROM WEB_SALES 
    JOIN DATE_DIM ON WS_SOLD_DATE_SK = D_DATE_SK 
    WHERE NOT EXISTS (
        SELECT 1 FROM WEB_RETURNS 
        WHERE WR_ORDER_NUMBER = WS_ORDER_NUMBER AND WS_ITEM_SK = WR_ITEM_SK
    )
    AND D_YEAR = 2001
    GROUP BY WS_ITEM_SK, WS_BILL_CUSTOMER_SK
), 
CS AS ( 
    SELECT CS_ITEM_SK
           , CS_BILL_CUSTOMER_SK CS_CUSTOMER_SK
           , SUM(CS_QUANTITY) CS_QTY
           , SUM(CS_WHOLESALE_COST) CS_WC
           , SUM(CS_SALES_PRICE) CS_SP 
    FROM CATALOG_SALES 
    JOIN DATE_DIM ON CS_SOLD_DATE_SK = D_DATE_SK 
    WHERE NOT EXISTS (
        SELECT 1 FROM CATALOG_RETURNS 
        WHERE CR_ORDER_NUMBER = CS_ORDER_NUMBER AND CS_ITEM_SK = CR_ITEM_SK
    )
    AND D_YEAR = 2001
    GROUP BY CS_ITEM_SK, CS_BILL_CUSTOMER_SK
), 
SS AS ( 
    SELECT SS_ITEM_SK
           , SS_CUSTOMER_SK
           , SUM(SS_QUANTITY) SS_QTY
           , SUM(SS_WHOLESALE_COST) SS_WC
           , SUM(SS_SALES_PRICE) SS_SP 
    FROM STORE_SALES 
    JOIN DATE_DIM ON SS_SOLD_DATE_SK = D_DATE_SK 
    WHERE NOT EXISTS (
        SELECT 1 FROM STORE_RETURNS 
        WHERE SR_TICKET_NUMBER = SS_TICKET_NUMBER AND SS_ITEM_SK = SR_ITEM_SK
    )
    AND D_YEAR = 2001
    GROUP BY SS_ITEM_SK, SS_CUSTOMER_SK
)  
SELECT  SS_CUSTOMER_SK
        , ROUND(SS_QTY/(IFNULL(WS_QTY,0)+IFNULL(CS_QTY,0)),2) RATIO
        , SS_QTY STORE_QTY
        , SS_WC STORE_WHOLESALE_COST
        , SS_SP STORE_SALES_PRICE
        , IFNULL(WS_QTY, 0) + IFNULL(CS_QTY, 0) OTHER_CHAN_QTY
        , IFNULL(WS_WC, 0) + IFNULL(CS_WC, 0) OTHER_CHAN_WHOLESALE_COST
        , IFNULL(WS_SP, 0) + IFNULL(CS_SP, 0) OTHER_CHAN_SALES_PRICE 
FROM SS 
LEFT JOIN WS ON WS_ITEM_SK = SS_ITEM_SK AND WS_CUSTOMER_SK = SS_CUSTOMER_SK
LEFT JOIN CS ON CS_ITEM_SK = SS_ITEM_SK AND CS_CUSTOMER_SK = SS_CUSTOMER_SK
WHERE (IFNULL(WS_QTY, 0) > 0 OR IFNULL(CS_QTY, 0) > 0)
ORDER BY RATIO DESC, SS_CUSTOMER_SK, SS_QTY DESC, SS_WC DESC, SS_SP DESC, OTHER_CHAN_QTY, OTHER_CHAN_WHOLESALE_COST, OTHER_CHAN_SALES_PRICE
LIMIT 100;
