WITH FREQUENT_SS_ITEMS AS (
    SELECT
        I_ITEM_SK
    FROM STORE_SALES
    JOIN DATE_DIM ON SS_SOLD_DATE_SK = D_DATE_SK
    JOIN ITEM ON SS_ITEM_SK = I_ITEM_SK
    WHERE D_YEAR BETWEEN 2000 AND 2003
    GROUP BY I_ITEM_SK, D_DATE, SUBSTR(I_ITEM_DESC, 1, 30)
    HAVING COUNT(*) > 4
),
MAX_STORE_SALES AS (
    SELECT MAX(SSALES) TPCDS_CMAX
    FROM (
        SELECT C_CUSTOMER_SK, SUM(SS_QUANTITY * SS_SALES_PRICE) SSALES
        FROM STORE_SALES
        JOIN DATE_DIM ON SS_SOLD_DATE_SK = D_DATE_SK
        WHERE D_YEAR BETWEEN 2000 AND 2003
        GROUP BY C_CUSTOMER_SK
    ) temp1
),
BEST_SS_CUSTOMER AS (
    SELECT C_CUSTOMER_SK
    FROM STORE_SALES
    JOIN MAX_STORE_SALES
    GROUP BY C_CUSTOMER_SK
    HAVING SUM(SS_QUANTITY * SS_SALES_PRICE) > (95/100.0) * TPCDS_CMAX
)
SELECT SUM(CS_QUANTITY * CS_LIST_PRICE + WS_QUANTITY * WS_LIST_PRICE) SALES
FROM CATALOG_SALES
JOIN DATE_DIM ON CS_SOLD_DATE_SK = D_DATE_SK
LEFT JOIN WEB_SALES ON CS_BILL_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND CS_ITEM_SK = WS_ITEM_SK
JOIN FREQUENT_SS_ITEMS ON CS_ITEM_SK = ITEM_SK
JOIN BEST_SS_CUSTOMER ON CS_BILL_CUSTOMER_SK = C_CUSTOMER_SK
WHERE D_YEAR = 2000 AND D_MOY = 3
LIMIT 100;

WITH FREQUENT_SS_ITEMS AS (
    SELECT
        I_ITEM_SK
    FROM STORE_SALES
    JOIN DATE_DIM ON SS_SOLD_DATE_SK = D_DATE_SK
    JOIN ITEM ON SS_ITEM_SK = I_ITEM_SK
    WHERE D_YEAR BETWEEN 2000 AND 2003
    GROUP BY I_ITEM_SK, D_DATE, SUBSTR(I_ITEM_DESC, 1, 30)
    HAVING COUNT(*) > 4
),
MAX_STORE_SALES AS (
    SELECT MAX(SSALES) TPCDS_CMAX
    FROM (
        SELECT C_CUSTOMER_SK, SUM(SS_QUANTITY * SS_SALES_PRICE) SSALES
        FROM STORE_SALES
        JOIN DATE_DIM ON SS_SOLD_DATE_SK = D_DATE_SK
        WHERE D_YEAR BETWEEN 2000 AND 2003
        GROUP BY C_CUSTOMER_SK
    ) temp1
),
BEST_SS_CUSTOMER AS (
    SELECT C_CUSTOMER_SK
    FROM STORE_SALES
    JOIN MAX_STORE_SALES
    GROUP BY C_CUSTOMER_SK
    HAVING SUM(SS_QUANTITY * SS_SALES_PRICE) > (95/100.0) * TPCDS_CMAX
)
SELECT C_LAST_NAME, C_FIRST_NAME, SUM(CS_QUANTITY * CS_LIST_PRICE + WS_QUANTITY * WS_LIST_PRICE) SALES
FROM CATALOG_SALES
JOIN DATE_DIM ON CS_SOLD_DATE_SK = D_DATE_SK
JOIN CUSTOMER ON CS_BILL_CUSTOMER_SK = C_CUSTOMER_SK
LEFT JOIN WEB_SALES ON CS_BILL_CUSTOMER_SK = WS_BILL_CUSTOMER_SK AND CS_ITEM_SK = WS_ITEM_SK
JOIN FREQUENT_SS_ITEMS ON CS_ITEM_SK = ITEM_SK
JOIN BEST_SS_CUSTOMER ON CS_BILL_CUSTOMER_SK = C_CUSTOMER_SK
WHERE D_YEAR = 2000 AND D_MOY = 3
GROUP BY C_LAST_NAME, C_FIRST_NAME
ORDER BY C_LAST_NAME, C_FIRST_NAME, SALES
LIMIT 100;
