WITH SS AS ( 
   SELECT I_ITEM_ID
          , SUM(SS_EXT_SALES_PRICE) TOTAL_SALES 
   FROM DATE_DIM
        JOIN STORE_SALES 
        JOIN ITEM  
        JOIN CUSTOMER_ADDRESS 
   WHERE I_ITEM_ID IN ( 
            SELECT I_ITEM_ID FROM ITEM WHERE I_CATEGORY IN ( 'Children' ) ) 
         AND SS_ITEM_SK = I_ITEM_SK 
         AND SS_SOLD_DATE_SK = D_DATE_SK 
         AND D_YEAR = 1998 
         AND D_MOY = 10 
         AND SS_ADDR_SK = CA_ADDRESS_SK 
         AND CA_GMT_OFFSET = -5 
   GROUP BY I_ITEM_ID ) , 
CS AS ( 
   SELECT I_ITEM_ID
          , SUM(CS_EXT_SALES_PRICE) TOTAL_SALES 
   FROM DATE_DIM 
        JOIN CATALOG_SALES 
        JOIN ITEM  
        JOIN CUSTOMER_ADDRESS
   WHERE I_ITEM_ID IN ( 
            SELECT I_ITEM_ID FROM ITEM WHERE I_CATEGORY IN ( 'Children' ) ) 
         AND CS_ITEM_SK = I_ITEM_SK 
         AND CS_SOLD_DATE_SK = D_DATE_SK 
         AND D_YEAR = 1998 
         AND D_MOY = 10 
         AND CS_BILL_ADDR_SK = CA_ADDRESS_SK 
         AND CA_GMT_OFFSET = -5 
   GROUP BY I_ITEM_ID ) , 
WS AS ( 
   SELECT I_ITEM_ID
          , SUM(WS_EXT_SALES_PRICE) TOTAL_SALES 
   FROM DATE_DIM 
        JOIN WEB_SALES 
        JOIN ITEM  
        JOIN CUSTOMER_ADDRESS 
   WHERE I_ITEM_ID IN ( 
             SELECT I_ITEM_ID FROM ITEM WHERE I_CATEGORY IN ( 'Children' ) ) 
         AND WS_ITEM_SK = I_ITEM_SK
         AND WS_SOLD_DATE_SK = D_DATE_SK 
         AND D_YEAR = 1998 
         AND D_MOY = 10 
         AND WS_BILL_ADDR_SK = CA_ADDRESS_SK 
         AND CA_GMT_OFFSET = -5 
   GROUP BY I_ITEM_ID )  
SELECT  I_ITEM_ID
        , SUM(TOTAL_SALES) TOTAL_SALES 
FROM ( SELECT * FROM SS
       UNION ALL 
       SELECT * FROM CS 
       UNION ALL 
       SELECT * FROM WS ) TMP1 
GROUP BY I_ITEM_ID 
ORDER BY I_ITEM_ID
         , TOTAL_SALES 
LIMIT 100;
